#!/usr/bin/env python3
"""Generate a versioned BLS OEWS national data source from an official XLSX file.

Usage:
  python3 scripts/update_bls_oews.py /path/to/national_M2025_dl.xlsx --year 2025

The script intentionally uses only the Python standard library so future data
refreshes do not require adding spreadsheet dependencies to the app.
"""

from __future__ import annotations

import argparse
import json
import re
import zipfile
from pathlib import Path
from typing import Any
from xml.etree import ElementTree


ROOT = Path(__file__).resolve().parents[1]
NS = {"a": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
SOURCE_URL = "https://www.bls.gov/oes/tables.htm"
COLUMNS = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "AA",
    "AB",
    "AC",
    "AD",
    "AE",
    "AF",
]


def load_shared_strings(workbook: zipfile.ZipFile) -> list[str]:
    root = ElementTree.fromstring(workbook.read("xl/sharedStrings.xml"))
    strings: list[str] = []

    for item in root.findall("a:si", NS):
        strings.append("".join(node.text or "" for node in item.findall(".//a:t", NS)))

    return strings


def read_cell_value(cell: ElementTree.Element, shared_strings: list[str]) -> Any:
    value_node = cell.find("a:v", NS)
    if value_node is None or value_node.text is None:
        return None

    value = value_node.text
    if cell.attrib.get("t") == "s":
        return shared_strings[int(value)]

    if re.fullmatch(r"-?\d+", value):
        return int(value)

    try:
        return float(value)
    except ValueError:
        return value


def read_workbook_rows(xlsx_path: Path) -> list[dict[str, Any]]:
    with zipfile.ZipFile(xlsx_path) as workbook:
        shared_strings = load_shared_strings(workbook)
        root = ElementTree.fromstring(workbook.read("xl/worksheets/sheet1.xml"))
        raw_rows: list[dict[str, Any]] = []

        for row in root.findall("a:sheetData/a:row", NS):
            values: dict[str, Any] = {}
            for cell in row.findall("a:c", NS):
                column = re.findall(r"[A-Z]+", cell.attrib["r"])[0]
                values[column] = read_cell_value(cell, shared_strings)
            raw_rows.append(values)

    headers = [raw_rows[0].get(column) for column in COLUMNS]
    return [dict(zip(headers, [row.get(column) for column in COLUMNS])) for row in raw_rows[1:]]


def as_number(value: Any) -> float | int | None:
    if isinstance(value, (int, float)):
        return value
    return None


def as_boolean(value: Any) -> bool:
    return str(value).strip().upper() == "TRUE"


def normalize_row(row: dict[str, Any], year: int) -> dict[str, Any]:
    return {
        "sourceYear": year,
        "sourcePeriod": f"May {year}",
        "sourceUrl": SOURCE_URL,
        "area": str(row["AREA"]),
        "areaTitle": row["AREA_TITLE"],
        "occCode": row["OCC_CODE"],
        "occTitle": row["OCC_TITLE"],
        "oGroup": row["O_GROUP"],
        "totalEmployment": as_number(row["TOT_EMP"]),
        "employmentPrse": as_number(row["EMP_PRSE"]),
        "hourlyMeanWage": as_number(row["H_MEAN"]),
        "annualMeanWage": as_number(row["A_MEAN"]),
        "meanWagePrse": as_number(row["MEAN_PRSE"]),
        "hourlyMedianWage": as_number(row["H_MEDIAN"]),
        "annualMedianWage": as_number(row["A_MEDIAN"]),
        "annualPercentile10": as_number(row["A_PCT10"]),
        "annualPercentile25": as_number(row["A_PCT25"]),
        "annualPercentile75": as_number(row["A_PCT75"]),
        "annualPercentile90": as_number(row["A_PCT90"]),
        "annualOnly": as_boolean(row["ANNUAL"]),
        "hourlyOnly": as_boolean(row["HOURLY"]),
    }


def write_ts_data(rows: list[dict[str, Any]], year: int) -> Path:
    output_path = ROOT / "src" / "lib" / "data" / f"bls-oews-{year}-national.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = f"""// Generated by scripts/update_bls_oews.py.
// Source: BLS OEWS national estimates, May {year}.
// Do not edit by hand; rerun the script with the official BLS XLSX file.

export type BlsOewsOccupation = {{
  sourceYear: number;
  sourcePeriod: string;
  sourceUrl: string;
  area: string;
  areaTitle: string;
  occCode: string;
  occTitle: string;
  oGroup: "total" | "major" | "minor" | "broad" | "detailed";
  totalEmployment: number | null;
  employmentPrse: number | null;
  hourlyMeanWage: number | null;
  annualMeanWage: number | null;
  meanWagePrse: number | null;
  hourlyMedianWage: number | null;
  annualMedianWage: number | null;
  annualPercentile10: number | null;
  annualPercentile25: number | null;
  annualPercentile75: number | null;
  annualPercentile90: number | null;
  annualOnly: boolean;
  hourlyOnly: boolean;
}};

export const blsOews{year}National = {json.dumps(rows, indent=2)} satisfies readonly BlsOewsOccupation[];
"""
    output_path.write_text(content, encoding="utf-8")
    return output_path


def load_current_occupations() -> list[dict[str, Any]]:
    source = (ROOT / "src" / "lib" / "data" / "occupations.ts").read_text(encoding="utf-8")
    match = re.search(r"export const occupations = (\[.*\]) satisfies", source, re.S)
    if not match:
        raise RuntimeError("Could not find exported occupations array.")
    return json.loads(match.group(1))


def build_match_review(rows: list[dict[str, Any]], year: int) -> tuple[dict[str, Any], dict[str, str]]:
    occupations = load_current_occupations()
    all_by_title: dict[str, list[dict[str, Any]]] = {}
    detailed_by_title: dict[str, list[dict[str, Any]]] = {}

    for row in rows:
        key = row["occTitle"].lower()
        all_by_title.setdefault(key, []).append(row)
        if row["oGroup"] == "detailed":
            detailed_by_title.setdefault(key, []).append(row)

    candidates: list[dict[str, Any]] = []
    map_candidates: dict[str, str] = {}

    for occupation in occupations:
        key = occupation["title"].lower()
        detailed_match = detailed_by_title.get(key, [])
        any_match = all_by_title.get(key, [])
        match_row = detailed_match[0] if detailed_match else any_match[0] if any_match else None

        if detailed_match:
            status = "exact-detailed"
        elif any_match:
            status = "exact-any-group"
        else:
            status = "unmatched"

        if match_row:
            map_candidates[occupation["slug"]] = match_row["occCode"]

        candidates.append(
            {
                "slug": occupation["slug"],
                "title": occupation["title"],
                "status": status,
                "currentPay": occupation["pay"],
                "currentJobs": occupation["jobs"],
                "oewsOccCode": match_row["occCode"] if match_row else None,
                "oewsOccTitle": match_row["occTitle"] if match_row else None,
                "oewsGroup": match_row["oGroup"] if match_row else None,
                "oewsAnnualMedianWage": match_row["annualMedianWage"] if match_row else None,
                "oewsTotalEmployment": match_row["totalEmployment"] if match_row else None,
            }
        )

    counts: dict[str, int] = {}
    for candidate in candidates:
        counts[candidate["status"]] = counts.get(candidate["status"], 0) + 1

    review = {
        "sourceYear": year,
        "sourcePeriod": f"May {year}",
        "sourceUrl": SOURCE_URL,
        "currentOccupationCount": len(occupations),
        "oewsRowCount": len(rows),
        "oewsDetailedRowCount": len([row for row in rows if row["oGroup"] == "detailed"]),
        "matchCounts": counts,
        "notes": [
            "Use exact-detailed rows first when promoting OEWS values into the app dataset.",
            "Review exact-any-group rows because they may be broad/minor/major SOC groups.",
            "Manually map unmatched rows before any active data replacement.",
        ],
        "candidates": candidates,
    }
    return review, map_candidates


def write_review(review: dict[str, Any], year: int) -> Path:
    output_path = ROOT / "docs" / "data" / f"bls-oews-{year}-match-review.json"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(review, indent=2) + "\n", encoding="utf-8")
    return output_path


def write_map_candidates(map_candidates: dict[str, str], year: int) -> Path:
    output_path = ROOT / "src" / "lib" / "data" / f"occupation-oews-{year}-map.ts"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "// Generated by scripts/update_bls_oews.py.",
        f"// Candidate title-based mappings from current occupation slugs to May {year} OEWS SOC codes.",
        "// Review before using this map to merge values into the active occupation dataset.",
        "",
        f"export const occupationOews{year}Map = {{",
    ]

    for slug in sorted(map_candidates):
        lines.append(f'  "{slug}": "{map_candidates[slug]}",')

    lines.extend(["} as const;", ""])
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a versioned BLS OEWS TypeScript data file.")
    parser.add_argument("xlsx", type=Path, help="Path to the official BLS national_MYYYY_dl.xlsx file.")
    parser.add_argument("--year", type=int, required=True, help="OEWS source year, for example 2025.")
    args = parser.parse_args()

    if not args.xlsx.exists():
        raise SystemExit(f"File not found: {args.xlsx}")

    rows = [normalize_row(row, args.year) for row in read_workbook_rows(args.xlsx)]
    data_path = write_ts_data(rows, args.year)
    review, map_candidates = build_match_review(rows, args.year)
    review_path = write_review(review, args.year)
    map_path = write_map_candidates(map_candidates, args.year)

    print(f"Wrote {data_path.relative_to(ROOT)} ({len(rows)} rows)")
    print(f"Wrote {map_path.relative_to(ROOT)} ({len(map_candidates)} candidate mappings)")
    print(f"Wrote {review_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
